### ISSUE TITLE
该怎么用Android Studio打开并运行这个项目呢？

### ISSUE THREAD

**Issue by Tong-c** [hejunlin2013/RedPackage#1]
download下完整的项目，直接用Android Studio打开，就会提示“Android framework is detected in the project”，无法运行

**Comment by hejunlin2013** [comment]
可以看下local.properties中是否设置对应sdk位置，如sdk.dir=D\:\\Android\\android-sdk

**Comment by hejunlin2013** [comment]
@Tong-c 可以看下local.properties中是否设置对应sdk位置，如sdk.dir=D:\Android\android-sdk

**Comment by jin404861445lan** [comment]
在学怎么用github，哈哈

**Comment by smartyuge** [comment]
@Tong-c 直接可用studio运行
